#include "plat_config_defs.h"
#include "mfpr_api.h"
#include "plat_basic_api.h"

/*pinmux default config*/
uint32 crane_default_cfg[] = {

	/*USIM2 function*/
	MFP_REG(GPIO_USIM2_UCLK) | MFP_AF0 | MFP_DRIVE_MEDIUM | MFP_PULL_HIGH | MFP_SLEEP_FLOAT | MFP_LPM_EDGE_NONE,
	MFP_REG(GPIO_USIM2_UIO) | MFP_AF0 | MFP_DRIVE_MEDIUM | MFP_PULL_HIGH | MFP_SLEEP_FLOAT | MFP_LPM_EDGE_NONE,
	MFP_REG(GPIO_USIM2_URSTn) | MFP_AF0 | MFP_DRIVE_MEDIUM | MFP_PULL_HIGH | MFP_SLEEP_FLOAT | MFP_LPM_EDGE_NONE,

	/*USIM function*/
	MFP_REG(GPIO_USIM_UCLK) | MFP_AF0 | MFP_DRIVE_MEDIUM | MFP_PULL_HIGH | MFP_SLEEP_FLOAT | MFP_LPM_EDGE_NONE,
	MFP_REG(GPIO_USIM_UIO) | MFP_AF0 | MFP_DRIVE_MEDIUM | MFP_PULL_HIGH | MFP_SLEEP_FLOAT | MFP_LPM_EDGE_NONE,
	MFP_REG(GPIO_USIM_URSTn) | MFP_AF0 | MFP_DRIVE_MEDIUM | MFP_PULL_HIGH | MFP_SLEEP_FLOAT | MFP_LPM_EDGE_NONE,

	/*DVL function*/
	MFP_REG(GPIO_TDS_DIO0_DVC_0) | MFP_AF0 | MFP_DRIVE_MEDIUM | MFP_PULL_LOW | MFP_SLEEP_NONE | MFP_LPM_EDGE_NONE,
	MFP_REG(GPIO_TDS_DIO1_DVC_1) | MFP_AF0 | MFP_DRIVE_MEDIUM | MFP_PULL_LOW | MFP_SLEEP_NONE | MFP_LPM_EDGE_NONE,

	/*MMC function*/
	MFP_REG(GPIO_MMC1_DAT3) | MFP_AF0 | MFP_DRIVE_MEDIUM | MFP_PULL_HIGH | MFP_SLEEP_FLOAT | MFP_LPM_EDGE_NONE,
	MFP_REG(GPIO_MMC1_DAT2) | MFP_AF0 | MFP_DRIVE_MEDIUM | MFP_PULL_HIGH | MFP_SLEEP_FLOAT | MFP_LPM_EDGE_NONE,
	MFP_REG(GPIO_MMC1_DAT1) | MFP_AF0 | MFP_DRIVE_MEDIUM | MFP_PULL_HIGH | MFP_SLEEP_FLOAT | MFP_LPM_EDGE_NONE,
	MFP_REG(GPIO_MMC1_DAT0) | MFP_AF0 | MFP_DRIVE_MEDIUM | MFP_PULL_HIGH | MFP_SLEEP_FLOAT | MFP_LPM_EDGE_NONE,
	MFP_REG(GPIO_MMC1_CMD) | MFP_AF0 | MFP_DRIVE_MEDIUM | MFP_PULL_HIGH | MFP_SLEEP_FLOAT | MFP_LPM_EDGE_NONE,
	MFP_REG(GPIO_MMC1_CLK) | MFP_AF0 | MFP_DRIVE_MEDIUM | MFP_PULL_LOW | MFP_SLEEP_FLOAT | MFP_LPM_EDGE_NONE,
	MFP_REG(GPIO_MMC1_CD) | MFP_AF0 | MFP_DRIVE_MEDIUM | MFP_PULL_HIGH | MFP_SLEEP_FLOAT | MFP_LPM_EDGE_NONE,

	/*Jtag function*/
	MFP_REG(GPIO_PRI_TDI) | MFP_AF0 | MFP_DRIVE_MEDIUM | MFP_PULL_HIGH | MFP_SLEEP_FLOAT | MFP_LPM_EDGE_NONE,
	MFP_REG(GPIO_PRI_TMS) | MFP_AF0 | MFP_DRIVE_MEDIUM | MFP_PULL_HIGH | MFP_SLEEP_FLOAT | MFP_LPM_EDGE_NONE,
	MFP_REG(GPIO_PRI_TCK) | MFP_AF0 | MFP_DRIVE_MEDIUM | MFP_PULL_LOW | MFP_SLEEP_FLOAT | MFP_LPM_EDGE_NONE,
	MFP_REG(GPIO_PRI_TDO) | MFP_AF0 | MFP_DRIVE_MEDIUM | MFP_PULL_HIGH | MFP_SLEEP_FLOAT | MFP_LPM_EDGE_NONE,

	/* Keypad */
	MFP_REG(GPIO_00) | MFP_AF1 | MFP_DRIVE_MEDIUM | MFP_PULL_LOW | MFP_SLEEP_DIR | MFP_LPM_EDGE_NONE ,
	MFP_REG(GPIO_01) | MFP_AF1 | MFP_DRIVE_MEDIUM | MFP_PULL_LOW | MFP_SLEEP_DIR | MFP_LPM_EDGE_NONE ,
	MFP_REG(GPIO_02) | MFP_AF1 | MFP_DRIVE_MEDIUM | MFP_PULL_LOW | MFP_SLEEP_DIR | MFP_LPM_EDGE_NONE ,
	MFP_REG(GPIO_03) | MFP_AF1 | MFP_DRIVE_MEDIUM | MFP_PULL_LOW | MFP_SLEEP_DIR | MFP_LPM_EDGE_NONE ,
	MFP_REG(GPIO_04) | MFP_AF1 | MFP_DRIVE_MEDIUM | MFP_PULL_LOW | MFP_SLEEP_DIR | MFP_LPM_EDGE_NONE,
	MFP_REG(GPIO_05) | MFP_AF1 | MFP_DRIVE_MEDIUM | MFP_PULL_LOW | MFP_SLEEP_DIR | MFP_LPM_EDGE_NONE,
	MFP_REG(GPIO_06) | MFP_AF1 | MFP_DRIVE_MEDIUM | MFP_PULL_LOW | MFP_SLEEP_DIR | MFP_LPM_EDGE_NONE,
	MFP_REG(GPIO_07) | MFP_AF1 | MFP_DRIVE_MEDIUM | MFP_PULL_LOW | MFP_SLEEP_DIR | MFP_LPM_EDGE_NONE,
	MFP_REG(GPIO_08) | MFP_AF2 | MFP_DRIVE_MEDIUM | MFP_PULL_LOW | MFP_SLEEP_DIR | MFP_LPM_EDGE_NONE,
	MFP_REG(GPIO_09) | MFP_AF2 | MFP_DRIVE_MEDIUM | MFP_PULL_LOW | MFP_SLEEP_DIR | MFP_LPM_EDGE_NONE,

	MFP_REG(GPIO_TDS_DIO9_QSPI_CS2) | MFP_AF1 | MFP_DRIVE_MEDIUM | MFP_PULL_LOW | MFP_SLEEP_FLOAT | MFP_LPM_EDGE_NONE,
	MFP_REG(GPIO_21) | MFP_AF6 | MFP_DRIVE_MEDIUM | MFP_PULL_LOW | MFP_SLEEP_FLOAT | MFP_LPM_EDGE_NONE,
	MFP_REG(GPIO_28) | MFP_AF6 | MFP_DRIVE_MEDIUM | MFP_PULL_LOW | MFP_SLEEP_FLOAT | MFP_LPM_EDGE_NONE,
	MFP_REG(GPIO_121) | MFP_AF3 | MFP_DRIVE_MEDIUM | MFP_PULL_HIGH | MFP_SLEEP_FLOAT | MFP_LPM_EDGE_NONE,
	MFP_REG(GPIO_122) | MFP_AF5 | MFP_DRIVE_MEDIUM | MFP_PULL_LOW | MFP_SLEEP_FLOAT | MFP_LPM_EDGE_NONE,
	MFP_REG(GPIO_124) | MFP_AF3 | MFP_DRIVE_MEDIUM | MFP_PULL_LOW | MFP_SLEEP_FLOAT | MFP_LPM_EDGE_NONE,

	MFP_REG(GPIO_20) | MFP_AF2 | MFP_DRIVE_MEDIUM | MFP_PULL_LOW | MFP_SLEEP_FLOAT | MFP_LPM_EDGE_NONE,
	MFP_REG(GPIO_22) | MFP_AF2 | MFP_DRIVE_MEDIUM | MFP_PULL_LOW | MFP_SLEEP_FLOAT | MFP_LPM_EDGE_NONE,
	MFP_REG(GPIO_23) | MFP_AF2 | MFP_DRIVE_MEDIUM | MFP_PULL_HIGH | MFP_SLEEP_FLOAT | MFP_LPM_EDGE_NONE,
	MFP_REG(GPIO_24) | MFP_AF2 | MFP_DRIVE_MEDIUM | MFP_PULL_LOW | MFP_SLEEP_FLOAT | MFP_LPM_EDGE_NONE,
	MFP_REG(GPIO_25) | MFP_AF2 | MFP_DRIVE_MEDIUM | MFP_PULL_LOW | MFP_SLEEP_FLOAT | MFP_LPM_EDGE_NONE,
	MFP_REG(GPIO_26) | MFP_AF2 | MFP_DRIVE_MEDIUM | MFP_PULL_LOW | MFP_SLEEP_FLOAT | MFP_LPM_EDGE_NONE,
	MFP_REG(GPIO_27) | MFP_AF2 | MFP_DRIVE_MEDIUM | MFP_PULL_LOW | MFP_SLEEP_FLOAT | MFP_LPM_EDGE_NONE,
	MFP_REG(GPIO_31) | MFP_AF3 | MFP_DRIVE_MEDIUM | MFP_PULL_HIGH | MFP_SLEEP_FLOAT | MFP_LPM_EDGE_NONE,
	MFP_REG(GPIO_32) | MFP_AF3 | MFP_DRIVE_MEDIUM | MFP_PULL_HIGH | MFP_SLEEP_FLOAT | MFP_LPM_EDGE_NONE,
#if 0
	/*QSPI function*/
	MFP_REG(GPIO_TDS_DIO4_QSPI_DAT3) | MFP_AF0 | MFP_DRIVE_MEDIUM | MFP_PULL_LOW | MFP_SLEEP_FLOAT | MFP_LPM_EDGE_NONE,
	MFP_REG(GPIO_TDS_DIO5_QSPI_DAT2) | MFP_AF0 | MFP_DRIVE_MEDIUM | MFP_PULL_LOW | MFP_SLEEP_FLOAT | MFP_LPM_EDGE_NONE,
	MFP_REG(GPIO_TDS_DIO6_QSPI_DAT1) | MFP_AF0 | MFP_DRIVE_MEDIUM | MFP_PULL_LOW | MFP_SLEEP_FLOAT | MFP_LPM_EDGE_NONE,
	MFP_REG(GPIO_TDS_DIO7_QSPI_DAT0) | MFP_AF0 | MFP_DRIVE_MEDIUM | MFP_PULL_LOW | MFP_SLEEP_FLOAT | MFP_LPM_EDGE_NONE,
	MFP_REG(GPIO_TDS_CLK_QSPI_CLK) | MFP_AF0 | MFP_DRIVE_MEDIUM | MFP_PULL_LOW | MFP_SLEEP_FLOAT | MFP_LPM_EDGE_NONE,
	MFP_REG(GPIO_TDS_DIO8_QSPI_CS1) | MFP_AF0 | MFP_DRIVE_MEDIUM | MFP_PULL_LOW | MFP_SLEEP_FLOAT | MFP_LPM_EDGE_NONE,
#endif

	/*Camera function*/
	MFP_REG(GPIO_69_TDS_DIO2) | MFP_AF0 | MFP_DRIVE_MEDIUM | MFP_PULL_HIGH | MFP_SLEEP_FLOAT | MFP_LPM_EDGE_NONE,
	MFP_REG(GPIO_70_TDS_DIO3) | MFP_AF0 | MFP_DRIVE_MEDIUM | MFP_PULL_HIGH | MFP_SLEEP_FLOAT | MFP_LPM_EDGE_NONE,
	MFP_REG(GPIO_61) | MFP_AF0 | MFP_DRIVE_MEDIUM | MFP_PULL_HIGH | MFP_SLEEP_FLOAT | MFP_LPM_EDGE_NONE,
	MFP_REG(GPIO_66) | MFP_AF0 | MFP_DRIVE_MEDIUM | MFP_PULL_HIGH | MFP_SLEEP_FLOAT | MFP_LPM_EDGE_NONE,
	MFP_REG(GPIO_81) | MFP_AF4 | MFP_DRIVE_MEDIUM | MFP_PULL_LOW | MFP_SLEEP_FLOAT | MFP_LPM_EDGE_NONE,
	MFP_REG(GPIO_82) | MFP_AF4 | MFP_DRIVE_MEDIUM | MFP_PULL_LOW | MFP_SLEEP_FLOAT | MFP_LPM_EDGE_NONE,
	MFP_REG(GPIO_83) | MFP_AF4 | MFP_DRIVE_MEDIUM | MFP_PULL_LOW | MFP_SLEEP_FLOAT | MFP_LPM_EDGE_NONE,
#if defined(CONFIG_BOARD_CUSTOM_B)
#if defined(CONFIG_BOARD_CUSTOM_B_V01) 
	/* Lock_isr,hyq modify*/
	MFP_REG(GPIO_84) | MFP_AF0 | MFP_DRIVE_MEDIUM | MFP_PULL_HIGH | MFP_SLEEP_NONE | MFP_LPM_EDGE_BOTH,
#endif
	/* Exit pa enable,hyq modify*/
	MFP_REG(GPIO_85) | MFP_AF0 | MFP_DRIVE_MEDIUM | MFP_PULL_LOW | MFP_SLEEP_NONE | MFP_LPM_EDGE_NONE,
#else
	MFP_REG(GPIO_84) | MFP_AF4 | MFP_DRIVE_MEDIUM | MFP_PULL_LOW | MFP_SLEEP_FLOAT | MFP_LPM_EDGE_NONE,
	MFP_REG(GPIO_85) | MFP_AF4 | MFP_DRIVE_MEDIUM | MFP_PULL_LOW | MFP_SLEEP_FLOAT | MFP_LPM_EDGE_NONE,
#endif
	MFP_REG(GPIO_86) | MFP_AF0 | MFP_DRIVE_MEDIUM | MFP_PULL_LOW | MFP_SLEEP_FLOAT | MFP_LPM_EDGE_NONE,

	MFP_REG(GPIO_TDS_DIO10_QSPI_DQM) | MFP_AF1 | MFP_DRIVE_MEDIUM | MFP_PULL_LOW | MFP_SLEEP_FLOAT | MFP_LPM_EDGE_NONE,
	MFP_REG(GPIO_71) | MFP_AF1 | MFP_DRIVE_MEDIUM | MFP_PULL_LOW | MFP_SLEEP_FLOAT | MFP_LPM_EDGE_NONE,
	MFP_REG(GPIO_72) | MFP_AF1 | MFP_DRIVE_MEDIUM | MFP_PULL_HIGH | MFP_SLEEP_FLOAT | MFP_LPM_EDGE_NONE,
	MFP_REG(GPIO_73) | MFP_AF1 | MFP_DRIVE_MEDIUM | MFP_PULL_HIGH | MFP_SLEEP_FLOAT | MFP_LPM_EDGE_NONE,
	MFP_REG(GPIO_74) | MFP_AF1 | MFP_DRIVE_MEDIUM | MFP_PULL_LOW | MFP_SLEEP_FLOAT | MFP_LPM_EDGE_NONE,

	MFP_REG(GPIO_75) | MFP_AF0 | MFP_DRIVE_MEDIUM | MFP_PULL_NONE | MFP_SLEEP_FLOAT | MFP_LPM_EDGE_NONE,
	MFP_REG(GPIO_76) | MFP_AF0 | MFP_DRIVE_MEDIUM | MFP_PULL_NONE | MFP_SLEEP_FLOAT | MFP_LPM_EDGE_NONE,
	MFP_REG(GPIO_77) | MFP_AF1 | MFP_DRIVE_MEDIUM | MFP_PULL_LOW | MFP_SLEEP_FLOAT | MFP_LPM_EDGE_NONE,
	MFP_REG(GPIO_78) | MFP_AF1 | MFP_DRIVE_MEDIUM | MFP_PULL_LOW | MFP_SLEEP_FLOAT | MFP_LPM_EDGE_NONE,
	
	/*lcd function: use 3wire 2data lane 1if as default*/
	MFP_REG(GPIO_22) | MFP_AF2 | MFP_DRIVE_MEDIUM | MFP_PULL_HIGH | MFP_SLEEP_DIR | MFP_LPM_EDGE_NONE, /*CS0*/
	MFP_REG(GPIO_26) | MFP_AF2 | MFP_DRIVE_MEDIUM | MFP_PULL_HIGH | MFP_SLEEP_DIR | MFP_LPM_EDGE_NONE, /*RST*/
	MFP_REG(GPIO_20) | MFP_AF2 | MFP_DRIVE_MEDIUM | MFP_PULL_HIGH | MFP_SLEEP_DIR | MFP_LPM_EDGE_NONE, /*SCLK*/
	MFP_REG(GPIO_24) | MFP_AF2 | MFP_DRIVE_MEDIUM | MFP_PULL_HIGH | MFP_SLEEP_DIR | MFP_LPM_EDGE_NONE, /*SDA*/
	MFP_REG(GPIO_27) | MFP_AF2 | MFP_DRIVE_MEDIUM | MFP_PULL_HIGH | MFP_SLEEP_DIR | MFP_LPM_EDGE_NONE, /*SDA2*/
#ifdef LCD_HAS_TE_SIGNAL
	MFP_REG(GPIO_25) | MFP_AF2 | MFP_DRIVE_MEDIUM | MFP_PULL_LOW | MFP_SLEEP_NONE | MFP_LPM_EDGE_NONE, /*TE*/
#endif	

	/*RF function*/
	MFP_REG(GPIO_62) | MFP_AF2 | MFP_DRIVE_MEDIUM | MFP_PULL_LOW | MFP_SLEEP_FLOAT | MFP_LPM_EDGE_NONE,
	MFP_REG(GPIO_63) | MFP_AF2 | MFP_DRIVE_MEDIUM | MFP_PULL_LOW | MFP_SLEEP_FLOAT | MFP_LPM_EDGE_NONE,
#ifdef CONFIG_BOARD_CUSTOM_B
	/*EN_FM - hyq modify*/
	MFP_REG(GPIO_64) | MFP_AF0 | MFP_DRIVE_MEDIUM | MFP_PULL_LOW | MFP_SLEEP_NONE | MFP_LPM_EDGE_NONE,
#else
	MFP_REG(GPIO_64) | MFP_AF2 | MFP_DRIVE_MEDIUM | MFP_PULL_LOW | MFP_SLEEP_FLOAT | MFP_LPM_EDGE_NONE,
#endif
	MFP_REG(GPIO_65) | MFP_AF2 | MFP_DRIVE_MEDIUM | MFP_PULL_LOW | MFP_SLEEP_FLOAT | MFP_LPM_EDGE_NONE,

	/*i2c function*/
	MFP_REG(GPIO_10) | MFP_AF1 | MFP_DRIVE_MEDIUM | MFP_PULL_HIGH | MFP_SLEEP_NONE | MFP_LPM_EDGE_NONE,
	MFP_REG(GPIO_11) | MFP_AF1 | MFP_DRIVE_MEDIUM | MFP_PULL_HIGH | MFP_SLEEP_NONE | MFP_LPM_EDGE_NONE,
	
	MFP_REG(GPIO_49) | MFP_AF0 | MFP_DRIVE_MEDIUM | MFP_PULL_LOW | MFP_SLEEP_NONE | MFP_LPM_EDGE_NONE,
	MFP_REG(GPIO_50) | MFP_AF0 | MFP_DRIVE_MEDIUM | MFP_PULL_LOW | MFP_SLEEP_NONE | MFP_LPM_EDGE_NONE,
	
	MFP_REG(GPIO_72) | MFP_AF1 | MFP_DRIVE_MEDIUM | MFP_PULL_HIGH | MFP_SLEEP_NONE | MFP_LPM_EDGE_NONE,
	MFP_REG(GPIO_73) | MFP_AF1 | MFP_DRIVE_MEDIUM | MFP_PULL_HIGH | MFP_SLEEP_NONE | MFP_LPM_EDGE_NONE,

	/*AP uart function*/
	MFP_REG(GPIO_29) | MFP_AF1 | MFP_DRIVE_MEDIUM | MFP_PULL_HIGH | MFP_SLEEP_NONE | MFP_LPM_EDGE_NONE,
	MFP_REG(GPIO_30) | MFP_AF1 | MFP_DRIVE_MEDIUM | MFP_PULL_HIGH | MFP_SLEEP_NONE | MFP_LPM_EDGE_NONE,

	/*cp uart*/
	MFP_REG(GPIO_51) | MFP_AF0 | MFP_DRIVE_MEDIUM | MFP_PULL_LOW | MFP_SLEEP_NONE | MFP_LPM_EDGE_NONE,
	MFP_REG(GPIO_52) | MFP_AF0 | MFP_DRIVE_MEDIUM | MFP_PULL_LOW | MFP_SLEEP_NONE | MFP_LPM_EDGE_NONE,
	
	MFP_REG(GPIO_53) | MFP_AF0 | MFP_DRIVE_MEDIUM | MFP_PULL_LOW | MFP_SLEEP_NONE | MFP_LPM_EDGE_NONE,
	MFP_REG(GPIO_54) | MFP_AF0 | MFP_DRIVE_MEDIUM | MFP_PULL_LOW | MFP_SLEEP_NONE | MFP_LPM_EDGE_NONE,


	/*PCM function on demand*/
	MFP_REG(GPIO_16) | MFP_AF0 | MFP_DRIVE_MEDIUM | MFP_PULL_LOW | MFP_SLEEP_NONE | MFP_LPM_EDGE_NONE,
	MFP_REG(GPIO_17) | MFP_AF0 | MFP_DRIVE_MEDIUM | MFP_PULL_LOW | MFP_SLEEP_NONE | MFP_LPM_EDGE_NONE,
	MFP_REG(GPIO_18) | MFP_AF0 | MFP_DRIVE_MEDIUM | MFP_PULL_LOW | MFP_SLEEP_NONE | MFP_LPM_EDGE_NONE,
	MFP_REG(GPIO_19) | MFP_AF0 | MFP_DRIVE_MEDIUM | MFP_PULL_LOW | MFP_SLEEP_NONE | MFP_LPM_EDGE_NONE,

	/*WIB function*/
	MFP_REG(GPIO_79_TDS_DIO11) | MFP_AF0 | MFP_DRIVE_MEDIUM | MFP_PULL_LOW | MFP_SLEEP_NONE | MFP_LPM_EDGE_NONE,
	MFP_REG(GPIO_80_TDS_DIO12) | MFP_AF0 | MFP_DRIVE_MEDIUM | MFP_PULL_LOW | MFP_SLEEP_NONE | MFP_LPM_EDGE_NONE,
	MFP_REG(GPIO_VCXO_REQ) | MFP_AF1 | MFP_DRIVE_MEDIUM | MFP_PULL_LOW | MFP_SLEEP_NONE | MFP_LPM_EDGE_NONE,
	
	/*codec intn function*/
	MFP_REG(CLK_REQ) | MFP_AF1 | MFP_DRIVE_MEDIUM | MFP_PULL_LOW | MFP_SLEEP_NONE | MFP_LPM_EDGE_NONE,

	/*VCXO function*/
	MFP_REG(GPIO_VCXO_OUT) | MFP_AF0 | MFP_DRIVE_MEDIUM | MFP_PULL_LOW | MFP_SLEEP_NONE | MFP_LPM_EDGE_NONE,

	/*Audio PA function*/
	MFP_REG(GPIO_60) | MFP_AF0 | MFP_DRIVE_MEDIUM | MFP_PULL_LOW | MFP_SLEEP_NONE | MFP_LPM_EDGE_NONE,

	/*wlan function*/
	MFP_REG(GPIO_TDS_DIO13_SDIO_DAT3) | MFP_AF0 | MFP_DRIVE_MEDIUM | MFP_PULL_HIGH | MFP_SLEEP_NONE | MFP_LPM_EDGE_NONE,
	MFP_REG(GPIO_TDS_DIO14_SDIO_DAT2) | MFP_AF0 | MFP_DRIVE_MEDIUM | MFP_PULL_HIGH | MFP_SLEEP_NONE | MFP_LPM_EDGE_NONE,
	MFP_REG(GPIO_TDS_DIO15_SDIO_DAT1) | MFP_AF0 | MFP_DRIVE_MEDIUM | MFP_PULL_HIGH | MFP_SLEEP_NONE | MFP_LPM_EDGE_NONE,
	MFP_REG(GPIO_TDS_DIO16_SDIO_DAT0) | MFP_AF0 | MFP_DRIVE_MEDIUM | MFP_PULL_HIGH | MFP_SLEEP_NONE | MFP_LPM_EDGE_NONE,
	MFP_REG(GPIO_TDS_DIO17_SDIO_CMD) | MFP_AF0 | MFP_DRIVE_MEDIUM | MFP_PULL_HIGH | MFP_SLEEP_NONE | MFP_LPM_EDGE_NONE,
	MFP_REG(GPIO_TDS_DIO18_SDIO_CLK) | MFP_AF0 | MFP_DRIVE_MEDIUM | MFP_PULL_HIGH | MFP_SLEEP_NONE | MFP_LPM_EDGE_NONE,

	/*SSP2 function*/
	MFP_REG(GPIO_12) | MFP_AF1 | MFP_DRIVE_MEDIUM | MFP_PULL_LOW | MFP_SLEEP_NONE | MFP_LPM_EDGE_NONE,
#if defined(CONFIG_BOARD_CUSTOM_B)
#if (!defined(CONFIG_BOARD_CUSTOM_B_V01) && !defined(CONFIG_BOARD_CUSTOM_B_V02))
	/* Lock_isr,hyq modify*/
	MFP_REG(GPIO_13) | MFP_AF0 | MFP_DRIVE_MEDIUM | MFP_PULL_HIGH | MFP_SLEEP_NONE | MFP_LPM_EDGE_BOTH,
	/* Exit pa enable,hyq modify*/
	MFP_REG(GPIO_14) | MFP_AF0 | MFP_DRIVE_MEDIUM | MFP_PULL_LOW | MFP_SLEEP_NONE | MFP_LPM_EDGE_NONE,
#else
	MFP_REG(GPIO_13) | MFP_AF1 | MFP_DRIVE_MEDIUM | MFP_PULL_LOW | MFP_SLEEP_NONE | MFP_LPM_EDGE_NONE,
	MFP_REG(GPIO_14) | MFP_AF1 | MFP_DRIVE_MEDIUM | MFP_PULL_LOW | MFP_SLEEP_NONE | MFP_LPM_EDGE_NONE,
#endif
#else
	MFP_REG(GPIO_13) | MFP_AF1 | MFP_DRIVE_MEDIUM | MFP_PULL_LOW | MFP_SLEEP_NONE | MFP_LPM_EDGE_NONE,
	MFP_REG(GPIO_14) | MFP_AF1 | MFP_DRIVE_MEDIUM | MFP_PULL_LOW | MFP_SLEEP_NONE | MFP_LPM_EDGE_NONE,
#endif
	MFP_REG(GPIO_15) | MFP_AF1 | MFP_DRIVE_MEDIUM | MFP_PULL_LOW | MFP_SLEEP_NONE | MFP_LPM_EDGE_NONE,
	/*SSP0 function*/
	MFP_REG(GPIO_33) | MFP_AF1 | MFP_DRIVE_MEDIUM | MFP_PULL_HIGH | MFP_SLEEP_NONE | MFP_LPM_EDGE_NONE,
	MFP_REG(GPIO_34) | MFP_AF1 | MFP_DRIVE_MEDIUM | MFP_PULL_HIGH | MFP_SLEEP_NONE | MFP_LPM_EDGE_NONE,
	MFP_REG(GPIO_35) | MFP_AF1 | MFP_DRIVE_MEDIUM | MFP_PULL_HIGH | MFP_SLEEP_NONE | MFP_LPM_EDGE_NONE,
	MFP_REG(GPIO_36) | MFP_AF1 | MFP_DRIVE_MEDIUM | MFP_PULL_HIGH | MFP_SLEEP_NONE | MFP_LPM_EDGE_NONE,
	MFP_EOC			/*End of configuration, must have */
};

const uint32 mfp_cfg_keypad_for_BOARD_CRANE_EVB[] = {
	/* Keypad */
	MFP_REG(GPIO_00) | MFP_AF1 | MFP_DRIVE_MEDIUM | MFP_PULL_LOW | MFP_SLEEP_DIR | MFP_LPM_EDGE_NONE ,
	MFP_REG(GPIO_01) | MFP_AF1 | MFP_DRIVE_MEDIUM | MFP_PULL_LOW | MFP_SLEEP_DIR | MFP_LPM_EDGE_NONE ,
	MFP_REG(GPIO_02) | MFP_AF1 | MFP_DRIVE_MEDIUM | MFP_PULL_LOW | MFP_SLEEP_DIR | MFP_LPM_EDGE_NONE ,
	MFP_REG(GPIO_03) | MFP_AF1 | MFP_DRIVE_MEDIUM | MFP_PULL_LOW | MFP_SLEEP_DIR | MFP_LPM_EDGE_NONE ,
	MFP_REG(GPIO_04) | MFP_AF1 | MFP_DRIVE_MEDIUM | MFP_PULL_LOW | MFP_SLEEP_DIR | MFP_LPM_EDGE_NONE,
	MFP_REG(GPIO_05) | MFP_AF1 | MFP_DRIVE_MEDIUM | MFP_PULL_LOW | MFP_SLEEP_DIR | MFP_LPM_EDGE_NONE,
	MFP_REG(GPIO_06) | MFP_AF1 | MFP_DRIVE_MEDIUM | MFP_PULL_LOW | MFP_SLEEP_DIR | MFP_LPM_EDGE_NONE,
	MFP_REG(GPIO_07) | MFP_AF1 | MFP_DRIVE_MEDIUM | MFP_PULL_LOW | MFP_SLEEP_DIR | MFP_LPM_EDGE_NONE,
	MFP_REG(GPIO_08) | MFP_AF2 | MFP_DRIVE_MEDIUM | MFP_PULL_LOW | MFP_SLEEP_DIR | MFP_LPM_EDGE_NONE,
	MFP_REG(GPIO_09) | MFP_AF2 | MFP_DRIVE_MEDIUM | MFP_PULL_LOW | MFP_SLEEP_DIR | MFP_LPM_EDGE_NONE,
	MFP_EOC			/*End of configuration, must have */
};

const uint32 mfp_cfg_keypad_for_BOARD_CRANE_PHONE[] = {
	/* Keypad */
	MFP_REG(GPIO_00) | MFP_AF1 | MFP_DRIVE_MEDIUM | MFP_PULL_LOW | MFP_SLEEP_DIR | MFP_LPM_EDGE_NONE ,
	MFP_REG(GPIO_01) | MFP_AF0 | MFP_DRIVE_MEDIUM | MFP_PULL_LOW | MFP_SLEEP_DIR | MFP_LPM_EDGE_NONE ,
	MFP_REG(GPIO_02) | MFP_AF1 | MFP_DRIVE_MEDIUM | MFP_PULL_LOW | MFP_SLEEP_DIR | MFP_LPM_EDGE_NONE ,
	MFP_REG(GPIO_03) | MFP_AF1 | MFP_DRIVE_MEDIUM | MFP_PULL_LOW | MFP_SLEEP_DIR | MFP_LPM_EDGE_NONE ,
	MFP_REG(GPIO_04) | MFP_AF1 | MFP_DRIVE_MEDIUM | MFP_PULL_LOW | MFP_SLEEP_DIR | MFP_LPM_EDGE_NONE,
	MFP_REG(GPIO_05) | MFP_AF1 | MFP_DRIVE_MEDIUM | MFP_PULL_LOW | MFP_SLEEP_DIR | MFP_LPM_EDGE_NONE,
	MFP_REG(GPIO_06) | MFP_AF1 | MFP_DRIVE_MEDIUM | MFP_PULL_LOW | MFP_SLEEP_DIR | MFP_LPM_EDGE_NONE,
	MFP_REG(GPIO_07) | MFP_AF1 | MFP_DRIVE_MEDIUM | MFP_PULL_LOW | MFP_SLEEP_DIR | MFP_LPM_EDGE_NONE,
	MFP_REG(GPIO_08) | MFP_AF2 | MFP_DRIVE_MEDIUM | MFP_PULL_LOW | MFP_SLEEP_DIR | MFP_LPM_EDGE_NONE,
	MFP_REG(GPIO_09) | MFP_AF2 | MFP_DRIVE_MEDIUM | MFP_PULL_LOW | MFP_SLEEP_DIR | MFP_LPM_EDGE_NONE,
	MFP_EOC			/*End of configuration, must have */
};

#if defined(CONFIG_BOARD_CUSTOM_G)
/*LCD backLight*/
uint32 mfp_cfg_lcdbl[] = {
	MFP_REG(GPIO_35) | MFP_AF0 | MFP_DRIVE_MEDIUM | MFP_PULL_LOW | MFP_SLEEP_FLOAT | MFP_LPM_EDGE_NONE,
	MFP_EOC
};
#endif
/*Torch Light*/
uint32 mfp_cfg_flash[] = {
	MFP_REG(GPIO_TDS_DIO10_QSPI_DQM) | MFP_AF1 | MFP_DRIVE_MEDIUM | MFP_PULL_LOW | MFP_SLEEP_FLOAT | MFP_LPM_EDGE_NONE,
	MFP_EOC
};

/*charger status*/
uint32 mfp_cfg_chgsts[] = {
	MFP_REG(GPIO_TDS_DIO16_SDIO_DAT0) | MFP_AF1 | MFP_DRIVE_MEDIUM | MFP_PULL_HIGH | MFP_SLEEP_FLOAT | MFP_LPM_EDGE_NONE,
	MFP_EOC
};

uint32 mfp_cfg_1601chgsts[] = {
//#if defined (CONFIG_BOARD_CRANE_EVB_PM802)
	MFP_REG(GPIO_83) | MFP_AF0 | MFP_DRIVE_MEDIUM | MFP_PULL_HIGH | MFP_SLEEP_FLOAT | MFP_LPM_EDGE_NONE,
	MFP_REG(GPIO_82) | MFP_AF0 | MFP_DRIVE_MEDIUM | MFP_PULL_LOW | MFP_SLEEP_DIR | MFP_LPM_EDGE_NONE,
	MFP_REG(GPIO_84) | MFP_AF0 | MFP_DRIVE_MEDIUM | MFP_PULL_HIGH | MFP_SLEEP_DIR | MFP_LPM_EDGE_NONE,
//#endif
	MFP_EOC
};
/*ISIM I2C function*/
uint32 mfp_cfg_isimi2c[] = {
	MFP_REG(GPIO_72) | MFP_AF1 | MFP_DRIVE_MEDIUM | MFP_PULL_HIGH| MFP_SLEEP_DIR | MFP_LPM_EDGE_NONE,
	MFP_REG(GPIO_73) | MFP_AF1 | MFP_DRIVE_MEDIUM | MFP_PULL_HIGH| MFP_SLEEP_DIR | MFP_LPM_EDGE_NONE,
	MFP_EOC
};

/*AP I2C functiont*/
uint32 mfp_cfg_api2c[] = {
	MFP_REG(GPIO_72) | MFP_AF2 | MFP_DRIVE_MEDIUM | MFP_PULL_HIGH| MFP_SLEEP_DIR | MFP_LPM_EDGE_NONE,
	MFP_REG(GPIO_73) | MFP_AF2 | MFP_DRIVE_MEDIUM | MFP_PULL_HIGH| MFP_SLEEP_DIR | MFP_LPM_EDGE_NONE,
	MFP_EOC
};

#if (!defined(CONFIG_BOARD_CUSTOM_B_V01) && !defined(CONFIG_BOARD_CUSTOM_B_V02))
/*Camera functiont*/
uint32 mfp_cfg_camera[] = {

#if defined (CONFIG_BOARD_CRANE_EVB_Z2) ||defined (CONFIG_BOARD_CRANE_EVB_Z3)
	MFP_REG(GPIO_69_TDS_DIO2) | MFP_AF0 | MFP_DRIVE_MEDIUM | MFP_PULL_LOW| MFP_SLEEP_DIR | MFP_LPM_EDGE_NONE,
	MFP_REG(GPIO_70_TDS_DIO3) | MFP_AF0 | MFP_DRIVE_MEDIUM | MFP_PULL_LOW | MFP_SLEEP_DIR | MFP_LPM_EDGE_NONE,
	MFP_REG(GPIO_61) | MFP_AF0 | MFP_DRIVE_MEDIUM | MFP_PULL_LOW | MFP_SLEEP_DIR | MFP_LPM_EDGE_NONE,
	MFP_REG(GPIO_66) | MFP_AF0 | MFP_DRIVE_MEDIUM | MFP_PULL_LOW | MFP_SLEEP_DIR | MFP_LPM_EDGE_NONE,
	MFP_REG(GPIO_71) | MFP_AF1 | MFP_DRIVE_MEDIUM | MFP_PULL_LOW | MFP_SLEEP_DIR | MFP_LPM_EDGE_NONE,
	MFP_REG(GPIO_72) | MFP_AF2 | MFP_DRIVE_MEDIUM | MFP_PULL_HIGH | MFP_SLEEP_DIR | MFP_LPM_EDGE_NONE,
	MFP_REG(GPIO_73) | MFP_AF2 | MFP_DRIVE_MEDIUM | MFP_PULL_HIGH | MFP_SLEEP_DIR | MFP_LPM_EDGE_NONE,

#endif
	MFP_REG(GPIO_81) | MFP_AF4 | MFP_DRIVE_MEDIUM | MFP_PULL_LOW | MFP_SLEEP_DIR | MFP_LPM_EDGE_NONE,
#ifdef CONFIG_BOARD_CUSTOM_V
	MFP_REG(GPIO_82) | MFP_AF0 | MFP_DRIVE_MEDIUM | MFP_PULL_LOW | MFP_SLEEP_DIR | MFP_LPM_EDGE_NONE,
#else
	MFP_REG(GPIO_82) | MFP_AF4 | MFP_DRIVE_MEDIUM | MFP_PULL_LOW | MFP_SLEEP_DIR | MFP_LPM_EDGE_NONE,
#endif
	MFP_REG(GPIO_83) | MFP_AF4 | MFP_DRIVE_MEDIUM | MFP_PULL_LOW | MFP_SLEEP_DIR | MFP_LPM_EDGE_NONE,
	MFP_REG(GPIO_84) | MFP_AF4 | MFP_DRIVE_MEDIUM | MFP_PULL_LOW | MFP_SLEEP_DIR | MFP_LPM_EDGE_NONE,
	MFP_REG(GPIO_85) | MFP_AF4 | MFP_DRIVE_MEDIUM | MFP_PULL_LOW | MFP_SLEEP_DIR | MFP_LPM_EDGE_NONE,
#ifdef CONFIG_BOARD_CUSTOM_V
	MFP_REG(GPIO_86) | MFP_AF0 | MFP_DRIVE_MEDIUM | MFP_PULL_LOW | MFP_SLEEP_DIR | MFP_LPM_EDGE_NONE,
#else
	MFP_REG(GPIO_86) | MFP_AF4 | MFP_DRIVE_MEDIUM | MFP_PULL_LOW | MFP_SLEEP_DIR | MFP_LPM_EDGE_NONE,
#endif


	MFP_REG(GPIO_74) | MFP_AF1 | MFP_DRIVE_MEDIUM | MFP_PULL_LOW | MFP_SLEEP_DIR | MFP_LPM_EDGE_NONE,
	MFP_REG(GPIO_75) | MFP_AF1 | MFP_DRIVE_MEDIUM | MFP_PULL_LOW | MFP_SLEEP_DIR | MFP_LPM_EDGE_NONE,
	MFP_REG(GPIO_76) | MFP_AF1 | MFP_DRIVE_MEDIUM | MFP_PULL_LOW | MFP_SLEEP_DIR | MFP_LPM_EDGE_NONE,
	MFP_REG(GPIO_77) | MFP_AF1 | MFP_DRIVE_MEDIUM | MFP_PULL_LOW | MFP_SLEEP_DIR | MFP_LPM_EDGE_NONE,
	MFP_REG(GPIO_78) | MFP_AF1 | MFP_DRIVE_MEDIUM | MFP_PULL_LOW | MFP_SLEEP_DIR | MFP_LPM_EDGE_NONE,
	MFP_EOC
};
/*Camera dvp interface functiont*/
uint32 mfp_cfg_camera_dvp[] = {

#if defined (CONFIG_BOARD_CRANE_EVB_Z2) ||defined (CONFIG_BOARD_CRANE_EVB_Z3)
	MFP_REG(GPIO_69_TDS_DIO2) | MFP_AF0 | MFP_DRIVE_MEDIUM | MFP_PULL_LOW| MFP_SLEEP_DIR | MFP_LPM_EDGE_NONE,
	MFP_REG(GPIO_70_TDS_DIO3) | MFP_AF0 | MFP_DRIVE_MEDIUM | MFP_PULL_LOW | MFP_SLEEP_DIR | MFP_LPM_EDGE_NONE,
	MFP_REG(GPIO_61) | MFP_AF0 | MFP_DRIVE_MEDIUM | MFP_PULL_LOW | MFP_SLEEP_DIR | MFP_LPM_EDGE_NONE,
	MFP_REG(GPIO_66) | MFP_AF0 | MFP_DRIVE_MEDIUM | MFP_PULL_LOW | MFP_SLEEP_DIR | MFP_LPM_EDGE_NONE,
	MFP_REG(GPIO_71) | MFP_AF1 | MFP_DRIVE_MEDIUM | MFP_PULL_LOW | MFP_SLEEP_DIR | MFP_LPM_EDGE_NONE,
	MFP_REG(GPIO_72) | MFP_AF2 | MFP_DRIVE_MEDIUM | MFP_PULL_HIGH | MFP_SLEEP_DIR | MFP_LPM_EDGE_NONE,
	MFP_REG(GPIO_73) | MFP_AF2 | MFP_DRIVE_MEDIUM | MFP_PULL_HIGH | MFP_SLEEP_DIR | MFP_LPM_EDGE_NONE,

#endif
	MFP_REG(GPIO_81) | MFP_AF4 | MFP_DRIVE_MEDIUM | MFP_PULL_LOW | MFP_SLEEP_DIR | MFP_LPM_EDGE_NONE,
#ifdef CONFIG_BOARD_CUSTOM_V
	MFP_REG(GPIO_82) | MFP_AF0 | MFP_DRIVE_MEDIUM | MFP_PULL_LOW | MFP_SLEEP_DIR | MFP_LPM_EDGE_NONE,
#else
	MFP_REG(GPIO_82) | MFP_AF4 | MFP_DRIVE_MEDIUM | MFP_PULL_LOW | MFP_SLEEP_DIR | MFP_LPM_EDGE_NONE,
#endif
	MFP_REG(GPIO_83) | MFP_AF4 | MFP_DRIVE_MEDIUM | MFP_PULL_LOW | MFP_SLEEP_DIR | MFP_LPM_EDGE_NONE,
	MFP_REG(GPIO_84) | MFP_AF4 | MFP_DRIVE_MEDIUM | MFP_PULL_LOW | MFP_SLEEP_DIR | MFP_LPM_EDGE_NONE,
	MFP_REG(GPIO_85) | MFP_AF4 | MFP_DRIVE_MEDIUM | MFP_PULL_LOW | MFP_SLEEP_DIR | MFP_LPM_EDGE_NONE,
#ifdef CONFIG_BOARD_CUSTOM_V
	MFP_REG(GPIO_86) | MFP_AF0 | MFP_DRIVE_MEDIUM | MFP_PULL_LOW | MFP_SLEEP_DIR | MFP_LPM_EDGE_NONE,
#else
	MFP_REG(GPIO_86) | MFP_AF4 | MFP_DRIVE_MEDIUM | MFP_PULL_LOW | MFP_SLEEP_DIR | MFP_LPM_EDGE_NONE,
#endif

	MFP_REG(GPIO_74) | MFP_AF4 | MFP_DRIVE_MEDIUM | MFP_PULL_LOW | MFP_SLEEP_DIR | MFP_LPM_EDGE_NONE,
	MFP_REG(GPIO_75) | MFP_AF4 | MFP_DRIVE_MEDIUM | MFP_PULL_LOW | MFP_SLEEP_DIR | MFP_LPM_EDGE_NONE,
	MFP_REG(GPIO_76) | MFP_AF4 | MFP_DRIVE_MEDIUM | MFP_PULL_LOW | MFP_SLEEP_DIR | MFP_LPM_EDGE_NONE,
	MFP_REG(GPIO_77) | MFP_AF4 | MFP_DRIVE_MEDIUM | MFP_PULL_LOW | MFP_SLEEP_DIR | MFP_LPM_EDGE_NONE,
	MFP_REG(GPIO_78) | MFP_AF4 | MFP_DRIVE_MEDIUM | MFP_PULL_LOW | MFP_SLEEP_DIR | MFP_LPM_EDGE_NONE,
	MFP_EOC
};
#else

uint32 mfp_cfg_camera[] = {
	MFP_EOC
};

/*Camera dvp interface functiont*/
uint32 mfp_cfg_camera_dvp[] = {
	MFP_EOC
};

#endif

#if defined (CONFIG_BOARD_CRANE_EVB_Z2) ||defined (CONFIG_BOARD_CRANE_EVB_Z3)
/*spi 3wire 1data lane 1interface function*/
uint32 mfp_cfg_lcd_spi_3w_1l_1if[] = {
	MFP_REG(GPIO_22) | MFP_AF2 | MFP_DRIVE_MEDIUM | MFP_PULL_HIGH | MFP_SLEEP_DIR | MFP_LPM_EDGE_NONE, /*CS0*/
#ifdef LCD_DUAL_PANEL_SUPPORT
	MFP_REG(GPIO_10) | MFP_AF7 | MFP_DRIVE_MEDIUM | MFP_PULL_HIGH | MFP_SLEEP_DIR | MFP_LPM_EDGE_NONE, /*CS1*/
#endif
	MFP_REG(GPIO_26) | MFP_AF2 | MFP_DRIVE_MEDIUM | MFP_PULL_HIGH | MFP_SLEEP_DIR | MFP_LPM_EDGE_NONE, /*RST*/
	MFP_REG(GPIO_20) | MFP_AF2 | MFP_DRIVE_MEDIUM | MFP_PULL_HIGH | MFP_SLEEP_DIR | MFP_LPM_EDGE_NONE, /*SCLK*/
	MFP_REG(GPIO_24) | MFP_AF2 | MFP_DRIVE_MEDIUM | MFP_PULL_HIGH | MFP_SLEEP_DIR | MFP_LPM_EDGE_NONE, /*SDA*/
#ifdef LCD_HAS_TE_SIGNAL
	MFP_REG(GPIO_25) | MFP_AF2 | MFP_DRIVE_MEDIUM | MFP_PULL_LOW | MFP_SLEEP_DIR | MFP_LPM_EDGE_NONE, /*TE*/
#endif	
	MFP_EOC
};

/*spi 3wire 2data lane 1interface function*/
uint32 mfp_cfg_lcd_spi_3w_2l_1if[] = {
	MFP_REG(GPIO_22) | MFP_AF2 | MFP_DRIVE_MEDIUM | MFP_PULL_HIGH | MFP_SLEEP_DIR | MFP_LPM_EDGE_NONE, /*CS0*/
#ifdef LCD_DUAL_PANEL_SUPPORT
	MFP_REG(GPIO_10) | MFP_AF7 | MFP_DRIVE_MEDIUM | MFP_PULL_HIGH | MFP_SLEEP_DIR | MFP_LPM_EDGE_NONE, /*CS1*/
#endif
	MFP_REG(GPIO_26) | MFP_AF2 | MFP_DRIVE_MEDIUM | MFP_PULL_HIGH | MFP_SLEEP_DIR | MFP_LPM_EDGE_NONE, /*RST*/
	MFP_REG(GPIO_20) | MFP_AF2 | MFP_DRIVE_MEDIUM | MFP_PULL_HIGH | MFP_SLEEP_DIR | MFP_LPM_EDGE_NONE, /*SCLK*/
	MFP_REG(GPIO_24) | MFP_AF2 | MFP_DRIVE_MEDIUM | MFP_PULL_HIGH | MFP_SLEEP_DIR | MFP_LPM_EDGE_NONE, /*SDA*/
	MFP_REG(GPIO_27) | MFP_AF2 | MFP_DRIVE_MEDIUM | MFP_PULL_HIGH | MFP_SLEEP_DIR | MFP_LPM_EDGE_NONE, /*SDA2*/
#ifdef LCD_HAS_TE_SIGNAL
	MFP_REG(GPIO_25) | MFP_AF2 | MFP_DRIVE_MEDIUM | MFP_PULL_LOW | MFP_SLEEP_NONE | MFP_LPM_EDGE_NONE, /*TE*/
#endif	
	MFP_EOC
};

/*spi 3wire 1data lane 2interface function*/
uint32 mfp_cfg_lcd_spi_3w_1l_2if[] = {
	MFP_REG(GPIO_22) | MFP_AF2 | MFP_DRIVE_MEDIUM | MFP_PULL_HIGH | MFP_SLEEP_DIR | MFP_LPM_EDGE_NONE, /*CS0*/
#ifdef LCD_DUAL_PANEL_SUPPORT
	MFP_REG(GPIO_10) | MFP_AF7 | MFP_DRIVE_MEDIUM | MFP_PULL_HIGH | MFP_SLEEP_DIR | MFP_LPM_EDGE_NONE, /*CS1*/
#endif
	MFP_REG(GPIO_26) | MFP_AF2 | MFP_DRIVE_MEDIUM | MFP_PULL_HIGH | MFP_SLEEP_DIR | MFP_LPM_EDGE_NONE, /*RST*/
	MFP_REG(GPIO_20) | MFP_AF2 | MFP_DRIVE_MEDIUM | MFP_PULL_HIGH | MFP_SLEEP_DIR | MFP_LPM_EDGE_NONE, /*SCLK*/
	MFP_REG(GPIO_24) | MFP_AF2 | MFP_DRIVE_MEDIUM | MFP_PULL_HIGH | MFP_SLEEP_DIR | MFP_LPM_EDGE_NONE, /*SDA*/
	MFP_REG(GPIO_23) | MFP_AF2 | MFP_DRIVE_MEDIUM | MFP_PULL_HIGH | MFP_SLEEP_DIR | MFP_LPM_EDGE_NONE, /*SDIn*/
#ifdef LCD_HAS_TE_SIGNAL
	MFP_REG(GPIO_25) | MFP_AF2 | MFP_DRIVE_MEDIUM | MFP_PULL_LOW | MFP_SLEEP_DIR | MFP_LPM_EDGE_NONE, /*TE*/
#endif	
	MFP_EOC
};

/*spi 3wire 2data lane 2interface function*/
uint32 mfp_cfg_lcd_spi_3w_2l_2if[] = {
	MFP_REG(GPIO_22) | MFP_AF2 | MFP_DRIVE_MEDIUM | MFP_PULL_HIGH | MFP_SLEEP_DIR | MFP_LPM_EDGE_NONE, /*CS0*/
#ifdef LCD_DUAL_PANEL_SUPPORT
	MFP_REG(GPIO_10) | MFP_AF7 | MFP_DRIVE_MEDIUM | MFP_PULL_HIGH | MFP_SLEEP_DIR | MFP_LPM_EDGE_NONE, /*CS1*/
#endif
	MFP_REG(GPIO_26) | MFP_AF2 | MFP_DRIVE_MEDIUM | MFP_PULL_HIGH | MFP_SLEEP_DIR | MFP_LPM_EDGE_NONE, /*RST*/
	MFP_REG(GPIO_20) | MFP_AF2 | MFP_DRIVE_MEDIUM | MFP_PULL_HIGH | MFP_SLEEP_DIR | MFP_LPM_EDGE_NONE, /*SCLK*/
	MFP_REG(GPIO_24) | MFP_AF2 | MFP_DRIVE_MEDIUM | MFP_PULL_HIGH | MFP_SLEEP_DIR | MFP_LPM_EDGE_NONE, /*SDA*/
	MFP_REG(GPIO_27) | MFP_AF2 | MFP_DRIVE_MEDIUM | MFP_PULL_HIGH | MFP_SLEEP_DIR | MFP_LPM_EDGE_NONE, /*SDA2*/
	MFP_REG(GPIO_23) | MFP_AF2 | MFP_DRIVE_MEDIUM | MFP_PULL_HIGH | MFP_SLEEP_DIR | MFP_LPM_EDGE_NONE, /*SDIn*/
#ifdef LCD_HAS_TE_SIGNAL
	MFP_REG(GPIO_25) | MFP_AF2 | MFP_DRIVE_MEDIUM | MFP_PULL_LOW | MFP_SLEEP_NONE | MFP_LPM_EDGE_NONE, /*TE*/
#endif	
	MFP_EOC
};


/*spi 4wire 1data lane 1interface function*/
uint32 mfp_cfg_lcd_spi_4w_1l_1if[] = {
	MFP_REG(GPIO_22) | MFP_AF2 | MFP_DRIVE_MEDIUM | MFP_PULL_HIGH | MFP_SLEEP_DIR | MFP_LPM_EDGE_NONE, /*CS0*/
#ifdef LCD_DUAL_PANEL_SUPPORT
	MFP_REG(GPIO_10) | MFP_AF7 | MFP_DRIVE_MEDIUM | MFP_PULL_HIGH | MFP_SLEEP_DIR | MFP_LPM_EDGE_NONE, /*CS1*/
#endif
	MFP_REG(GPIO_26) | MFP_AF2 | MFP_DRIVE_MEDIUM | MFP_PULL_HIGH | MFP_SLEEP_DIR | MFP_LPM_EDGE_NONE, /*RST*/
	MFP_REG(GPIO_20) | MFP_AF2 | MFP_DRIVE_MEDIUM | MFP_PULL_HIGH | MFP_SLEEP_DIR | MFP_LPM_EDGE_NONE, /*SCLK*/
	MFP_REG(GPIO_24) | MFP_AF2 | MFP_DRIVE_MEDIUM | MFP_PULL_HIGH | MFP_SLEEP_DIR | MFP_LPM_EDGE_NONE, /*SDA*/
#ifdef LCD_DCX_GPIO_27
	MFP_REG(GPIO_27) | MFP_AF0 | MFP_DRIVE_MEDIUM | MFP_PULL_HIGH | MFP_SLEEP_DIR | MFP_LPM_EDGE_NONE, /*DCX*/
#else /*use LCD_DCX_GPIO_21 as default*/
	MFP_REG(GPIO_21) | MFP_AF0 | MFP_DRIVE_MEDIUM | MFP_PULL_HIGH | MFP_SLEEP_DIR | MFP_LPM_EDGE_NONE, /*DCX*/
#endif
#ifdef LCD_HAS_TE_SIGNAL
	MFP_REG(GPIO_25) | MFP_AF2 | MFP_DRIVE_MEDIUM | MFP_PULL_LOW | MFP_SLEEP_DIR | MFP_LPM_EDGE_NONE, /*TE*/
#endif
#ifdef CONFIG_BOARD_CUSTOM_B_V02
	MFP_REG(GPIO_76) | MFP_AF0 | MFP_DRIVE_MEDIUM | MFP_PULL_LOW | MFP_SLEEP_DIR | MFP_LPM_EDGE_NONE, /*Backlight for Bird*/
#endif
	MFP_EOC
};

/*spi 4wire 1data lane 2interface function*/
uint32 mfp_cfg_lcd_spi_4w_1l_2if[] = {
	MFP_REG(GPIO_22) | MFP_AF2 | MFP_DRIVE_MEDIUM | MFP_PULL_HIGH | MFP_SLEEP_DIR | MFP_LPM_EDGE_NONE, /*CS0*/
#ifdef LCD_DUAL_PANEL_SUPPORT
	MFP_REG(GPIO_10) | MFP_AF7 | MFP_DRIVE_MEDIUM | MFP_PULL_HIGH | MFP_SLEEP_DIR | MFP_LPM_EDGE_NONE, /*CS1*/
#endif
	MFP_REG(GPIO_26) | MFP_AF2 | MFP_DRIVE_MEDIUM | MFP_PULL_HIGH | MFP_SLEEP_DIR | MFP_LPM_EDGE_NONE, /*RST*/
	MFP_REG(GPIO_20) | MFP_AF2 | MFP_DRIVE_MEDIUM | MFP_PULL_HIGH | MFP_SLEEP_DIR | MFP_LPM_EDGE_NONE, /*SCLK*/
	MFP_REG(GPIO_24) | MFP_AF2 | MFP_DRIVE_MEDIUM | MFP_PULL_HIGH | MFP_SLEEP_DIR | MFP_LPM_EDGE_NONE, /*SDA*/
	MFP_REG(GPIO_23) | MFP_AF2 | MFP_DRIVE_MEDIUM | MFP_PULL_HIGH | MFP_SLEEP_DIR | MFP_LPM_EDGE_NONE, /*SDIn*/
#ifdef LCD_DCX_GPIO_27
	MFP_REG(GPIO_27) | MFP_AF0 | MFP_DRIVE_MEDIUM | MFP_PULL_HIGH | MFP_SLEEP_DIR | MFP_LPM_EDGE_NONE, /*DCX*/
#else /*use LCD_DCX_GPIO_21 as default*/
	MFP_REG(GPIO_21) | MFP_AF0 | MFP_DRIVE_MEDIUM | MFP_PULL_HIGH | MFP_SLEEP_DIR | MFP_LPM_EDGE_NONE, /*DCX*/
#endif
#ifdef LCD_HAS_TE_SIGNAL
	MFP_REG(GPIO_25) | MFP_AF2 | MFP_DRIVE_MEDIUM | MFP_PULL_LOW | MFP_SLEEP_DIR | MFP_LPM_EDGE_NONE, /*TE*/
#endif	
	MFP_EOC
};

uint32 mfp_cfg_lcd_mcu[] = {
	MFP_REG(GPIO_22) | MFP_AF6 | MFP_DRIVE_MEDIUM | MFP_PULL_HIGH | MFP_SLEEP_DIR | MFP_LPM_EDGE_NONE, /*CS0*/
#ifdef LCD_DUAL_PANEL_SUPPORT
	MFP_REG(GPIO_11) | MFP_AF7 | MFP_DRIVE_MEDIUM | MFP_PULL_HIGH | MFP_SLEEP_DIR | MFP_LPM_EDGE_NONE, /*CS1*/
#endif
	MFP_REG(GPIO_26) | MFP_AF6 | MFP_DRIVE_MEDIUM | MFP_PULL_HIGH | MFP_SLEEP_DIR | MFP_LPM_EDGE_NONE, /*RST*/
	MFP_REG(GPIO_20) | MFP_AF6 | MFP_DRIVE_MEDIUM | MFP_PULL_HIGH | MFP_SLEEP_DIR | MFP_LPM_EDGE_NONE, /*DB0*/
	MFP_REG(GPIO_31) | MFP_AF3 | MFP_DRIVE_MEDIUM | MFP_PULL_HIGH | MFP_SLEEP_DIR | MFP_LPM_EDGE_NONE, /*DB1*/
	MFP_REG(GPIO_32) | MFP_AF3 | MFP_DRIVE_MEDIUM | MFP_PULL_HIGH | MFP_SLEEP_DIR | MFP_LPM_EDGE_NONE, /*DB2*/
	MFP_REG(GPIO_121) | MFP_AF3 | MFP_DRIVE_MEDIUM | MFP_PULL_HIGH | MFP_SLEEP_DIR | MFP_LPM_EDGE_NONE, /*DB3*/
	MFP_REG(GPIO_124) | MFP_AF3 | MFP_DRIVE_MEDIUM | MFP_PULL_HIGH | MFP_SLEEP_DIR | MFP_LPM_EDGE_NONE, /*DB4*/
	MFP_REG(GPIO_21) | MFP_AF6 | MFP_DRIVE_MEDIUM | MFP_PULL_HIGH | MFP_SLEEP_DIR | MFP_LPM_EDGE_NONE, /*DB5*/
	MFP_REG(GPIO_27) | MFP_AF6 | MFP_DRIVE_MEDIUM | MFP_PULL_HIGH | MFP_SLEEP_DIR | MFP_LPM_EDGE_NONE, /*DB6*/
	MFP_REG(GPIO_28) | MFP_AF6 | MFP_DRIVE_MEDIUM | MFP_PULL_HIGH | MFP_SLEEP_DIR | MFP_LPM_EDGE_NONE, /*DB7*/
	MFP_REG(GPIO_23) | MFP_AF6 | MFP_DRIVE_MEDIUM | MFP_PULL_HIGH | MFP_SLEEP_DIR | MFP_LPM_EDGE_NONE, /*RDB*/
	MFP_REG(GPIO_24) | MFP_AF6 | MFP_DRIVE_MEDIUM | MFP_PULL_HIGH | MFP_SLEEP_DIR | MFP_LPM_EDGE_NONE, /*WRB*/
	MFP_REG(GPIO_122) | MFP_AF5 | MFP_DRIVE_MEDIUM | MFP_PULL_HIGH | MFP_SLEEP_DIR | MFP_LPM_EDGE_NONE, /*DCX*/
#ifdef LCD_HAS_TE_SIGNAL
	MFP_REG(GPIO_25) | MFP_AF6 | MFP_DRIVE_MEDIUM | MFP_PULL_LOW | MFP_SLEEP_DIR | MFP_LPM_EDGE_NONE, /*TE*/
#endif	
	MFP_EOC
};
#else
/*spi 3wire 1data lane 1interface function*/
uint32 mfp_cfg_lcd_spi_3w_1l_1if[] = {
	/*need be added according to pin_config*/
	MFP_EOC
};

/*spi 3wire 2data lane 1interface function*/
uint32 mfp_cfg_lcd_spi_3w_2l_1if[] = {
	/*need be added according to pin_config*/
	MFP_EOC
};

/*spi 3wire 1data lane 2interface function*/
uint32 mfp_cfg_lcd_spi_3w_1l_2if[] = {
	/*need be added according to pin_config*/
	MFP_EOC
};

/*spi 3wire 2data lane 2interface function*/
uint32 mfp_cfg_lcd_spi_3w_2l_2if[] = {
	/*need be added according to pin_config*/
	MFP_EOC
};

/*spi 4wire 1data lane 1interface function*/
uint32 mfp_cfg_lcd_spi_4w_1l_1if[] = {
	/*need be added according to pin_config*/
	MFP_EOC
};

/*spi 4wire 1data lane 2interface function*/
uint32 mfp_cfg_lcd_spi_4w_1l_2if[] = {
	/*need be added according to pin_config*/
	MFP_EOC
};

uint32 mfp_cfg_lcd_mcu[] = {
	/*need be added according to pin_config*/
	MFP_EOC
};

#endif

/*wib i2c interface functiont*/
uint32 mfp_cfg_fm_iic[] = {
	MFP_REG(GPIO_49) | MFP_AF1 | MFP_DRIVE_MEDIUM | MFP_PULL_HIGH | MFP_SLEEP_NONE | MFP_LPM_EDGE_NONE,
	MFP_REG(GPIO_50) | MFP_AF1 | MFP_DRIVE_MEDIUM | MFP_PULL_HIGH | MFP_SLEEP_NONE | MFP_LPM_EDGE_NONE,
	MFP_EOC
};

/*wib i2c defualt gpio functiont*/
uint32 mfp_cfg_fm_gpio[] = {
	MFP_REG(GPIO_49) | MFP_AF0 | MFP_DRIVE_MEDIUM | MFP_PULL_LOW | MFP_SLEEP_NONE | MFP_LPM_EDGE_NONE,
	MFP_REG(GPIO_50) | MFP_AF0 | MFP_DRIVE_MEDIUM | MFP_PULL_LOW | MFP_SLEEP_NONE | MFP_LPM_EDGE_NONE,
	MFP_EOC
};

/*wib pin to bt functiont*/
uint32 mfp_cfg_for_bt[] = {
	/*WIB function*/
	MFP_REG(GPIO_79_TDS_DIO11) | MFP_AF0 | MFP_DRIVE_MEDIUM | MFP_PULL_HIGH | MFP_SLEEP_NONE | MFP_LPM_EDGE_NONE,
	MFP_REG(GPIO_80_TDS_DIO12) | MFP_AF0 | MFP_DRIVE_MEDIUM | MFP_PULL_LOW | MFP_SLEEP_NONE | MFP_LPM_EDGE_NONE,
	MFP_REG(GPIO_VCXO_REQ) | MFP_AF0 | MFP_DRIVE_MEDIUM | MFP_PULL_LOW | MFP_SLEEP_NONE | MFP_LPM_EDGE_NONE,
	MFP_REG(GPIO_86) | MFP_AF0 | MFP_DRIVE_MEDIUM | MFP_PULL_LOW | MFP_SLEEP_FLOAT | MFP_LPM_EDGE_NONE,
	MFP_REG(GPIO_51) | MFP_AF1 | MFP_DRIVE_MEDIUM | MFP_PULL_HIGH | MFP_SLEEP_NONE | MFP_LPM_EDGE_NONE,
	MFP_REG(GPIO_52) | MFP_AF1 | MFP_DRIVE_MEDIUM | MFP_PULL_HIGH | MFP_SLEEP_NONE | MFP_LPM_EDGE_NONE,
	MFP_REG(GPIO_53) | MFP_AF1 | MFP_DRIVE_MEDIUM | MFP_PULL_HIGH | MFP_SLEEP_NONE | MFP_LPM_EDGE_NONE,
	MFP_REG(GPIO_54) | MFP_AF1 | MFP_DRIVE_MEDIUM | MFP_PULL_HIGH | MFP_SLEEP_NONE | MFP_LPM_EDGE_NONE,
	MFP_EOC
};

/*wib pin to gpio functiont*/
uint32 mfp_cfg_for_bt_gpio[] = {
	/*WIB function*/
	MFP_REG(GPIO_79_TDS_DIO11) | MFP_AF0 | MFP_DRIVE_MEDIUM | MFP_PULL_LOW | MFP_SLEEP_NONE | MFP_LPM_EDGE_NONE,
	MFP_REG(GPIO_80_TDS_DIO12) | MFP_AF0 | MFP_DRIVE_MEDIUM | MFP_PULL_LOW | MFP_SLEEP_NONE | MFP_LPM_EDGE_NONE,
	MFP_REG(GPIO_VCXO_REQ) | MFP_AF1 | MFP_DRIVE_MEDIUM | MFP_PULL_LOW | MFP_SLEEP_NONE | MFP_LPM_EDGE_NONE,
	MFP_REG(GPIO_86) | MFP_AF0 | MFP_DRIVE_MEDIUM | MFP_PULL_LOW | MFP_SLEEP_FLOAT | MFP_LPM_EDGE_NONE,
	MFP_REG(GPIO_51) | MFP_AF0 | MFP_DRIVE_MEDIUM | MFP_PULL_HIGH | MFP_SLEEP_NONE | MFP_LPM_EDGE_NONE,
	MFP_REG(GPIO_52) | MFP_AF0 | MFP_DRIVE_MEDIUM | MFP_PULL_HIGH | MFP_SLEEP_NONE | MFP_LPM_EDGE_NONE,
	MFP_REG(GPIO_53) | MFP_AF0 | MFP_DRIVE_MEDIUM | MFP_PULL_HIGH | MFP_SLEEP_NONE | MFP_LPM_EDGE_NONE,
	MFP_REG(GPIO_54) | MFP_AF0 | MFP_DRIVE_MEDIUM | MFP_PULL_HIGH | MFP_SLEEP_NONE | MFP_LPM_EDGE_NONE,
	MFP_EOC
};

#if defined(CONFIG_BOARD_CUSTOM_G)
void LcdBlPinmuxcfg(void)
{
	mfp_config(mfp_cfg_lcdbl);
}
#endif

void CameraFlashPinmuxcfg(void)
{
	mfp_config(mfp_cfg_flash);
}

void KeypadPinmuxCfg(void)
{
	if(IS_HW_PLATFORM(BOARD_ID_CRANE_PHONE_V100))
		mfp_config((unsigned int*)mfp_cfg_keypad_for_BOARD_CRANE_PHONE);
	else
		mfp_config((unsigned int*)mfp_cfg_keypad_for_BOARD_CRANE_EVB);
}

void ChargerStsPinmuxCfg(void)
{
	mfp_config(mfp_cfg_chgsts);
}

void ChargerStsEvb1601_Pm802PinmuxCfg(void)
{
	mfp_config(mfp_cfg_1601chgsts);
}

void CameraI2CPinmuxCfg(uint32 flag)
{
	if(flag)
		mfp_config(mfp_cfg_isimi2c);
	else
		mfp_config(mfp_cfg_api2c);
}

void Camera_Pinmuxcfg(uint32 interface)
{
	if(2 == interface)
		mfp_config(mfp_cfg_camera_dvp);  // dvp interface
	else
		mfp_config(mfp_cfg_camera);
}

void LCD_Pinmuxcfg(uint32 interface)
{
	switch(interface){
	case 0: /*spi_3wire_1datalane_1if*/
		mfp_config(mfp_cfg_lcd_spi_3w_1l_1if);
		break;
	case 1: /*spi_3wire_2datalane_1if*/
		mfp_config(mfp_cfg_lcd_spi_3w_2l_1if);
		break;
	case 2: /*spi_3wire_1datalane_2if*/
		mfp_config(mfp_cfg_lcd_spi_3w_1l_2if);
		break;
	case 3: /*spi_3wire_2datalane_2if*/
		mfp_config(mfp_cfg_lcd_spi_3w_2l_2if);
		break;
	case 4: /*spi_4wire_1datalane_1if*/
		mfp_config(mfp_cfg_lcd_spi_4w_1l_1if);
		break;
	case 5: /*spi_4wire_1datalane_2if*/
		mfp_config(mfp_cfg_lcd_spi_4w_1l_2if);
		break;
	case 6: /*mcu*/
		mfp_config(mfp_cfg_lcd_mcu);
		break;
	default:/*Invalid case*/
		;
	}
}

void CraneDefaultPinConfig(void)
{
	mfp_config(crane_default_cfg);
	return;
}

void FmI2CPinConfig(uint8 on)
{
	if(on)
		mfp_config(mfp_cfg_fm_iic);
	else
		mfp_config(mfp_cfg_fm_gpio);
	return;
}


void BTPinConfig(uint8 on)
{
	if(on)
		mfp_config(mfp_cfg_for_bt);
	else
		mfp_config(mfp_cfg_for_bt_gpio);
	return;
}


