#ifndef ___TASK_CNF_H__
#define ___TASK_CNF_H__

// UI task priority interval: [UI_HIGHEST_PRIORITY, UI_LOWEST_PRIORITY]

#define UI_LOWEST_PRIORITY				250
#define UI_HIGHEST_PRIORITY				220

#define COS_PRI_BASE             		240
#define COS_PRI_PRV_BASE         		230

#define MMI_TASKS_PRIORITY_BASE			240
#ifdef DBG_CPU_MAX_TEST
#define MAX_CPU_TASK_SIZE				1024
#define MAX_CPU_TASK_PRIORITY			10
#endif

#define USK_TASK_STACK_SIZE				2048
#define USK_TASK_PRIO					50

#define RIL_READER_TASK_STACK_SIZE		4096
#define RIL_READER_TASK_PRIO			210

#define RILWORKER_TASK_STACK_SIZE		8192
#define RILWORKER_TASK_HIGH_PRIO		211
#define RILWORKER_TASK_MID_PRIO			212
#define RILWORKER_TASK_LOW_PRIO			221

#define RIL_DAEMON_TASK_STACK_SIZE		4096
#define RIL_DAEMON_TASK_PRIO			210

#define LCD_TASK_SIZE					2048
#define LCD_TASK_PRIORITY				220
#define LCD_ESD_TASK_PRIORITY			227

#define MMI_VIDEO_CODECS_SIZE 			4096
#define MMI_VIDEO_CODECS_TASK_PRIORITY	223
#define MMI_VIDEO_RECORDER_TASK_PRIORITY	45

#define ASYNFS_TASK_STACK_SIZE			2048
#define ASYNFS_TASK_PRIORITY 			224

#define CAMERA_PREVIEW_TASK_SIZE		2048
#define CAMERA_PREVIEW_TASK_PRIORITY	225

#define CAMERA_VIDEO_TASK_SIZE			2048
#define CAMERA_VIDEO_TASK_PRIORITY		225

#define CAMERA_IRQ_HANDLE_TASK_SIZE			2048
#define CAMERA_IRQ_HANDLE_TASK_PRIORITY		226

#define BAL_USB_MONITOR_TASK_STACK_SIZE	1024
#define BAL_DEV_MONITOR_TASK_STACK_SIZE	2048
#define BAL_DEV_MONITOR_TASK_PRIORITY   232

#define ADP_TASK_STACK_SIZE		        4096
#define ADP_TASK_PRIORITY		        241

#define NVRAM_TASK_STACK_SIZE			4096
#define NVRAM_TASK_PRIORITY				241

#define SMS_TASK_STACK_SIZE				4096
#define SMS_TASK_PRIORITY				246

#ifdef DBG_PERIOD_MONITOR
#define PERIOD_MONITOR_TASK_SIZE		1024
#define PERIOD_MONITOR_TASK_PRIORITY	242
#endif

#define MMI_MED_TASK_STACK_SIZE	        8192 * 2 //(soft jpeg encoder lib has many array)
#define MMI_MED_TASK_PRIORITY	        243

#define MMI_BTTASK_SIZE					4096
#define MMI_BTTASK_PRIORITY				244

#define MMI_TASK_STACK_SIZE		        (8192 * 2)
#define MMI_TASK_PRIORITY		        245

#define MMI_FSTASK_SIZE                 4096
#define MMI_FSTASK_PRIORITY				247

#define NVRAM_CACHE_TASK_STACK_SIZE		4096
#define NVRAM_CACHE_TASK_PRIORITY		247

#define GUI_DUMMY_TASK_STACK_SIZE		4096
#define GUI_DUMMY_TASK_PRIORITY			250

#define GUI_PLAY_RING_TASK_STACK_SIZE	2048
#define GUI_PLAY_RING_TASK_PRIORITY		250

#define LOGD_TASK_STACK_SIZE			1024
#define LOGD_TASK_PRIORITY				250

#ifdef CONFIG_UI_TASK_EXAMPLE
#define UI_EXAMPLE_TASK_STACK_SIZE		1024
#define UI_EXAMPLE_TASK_PRIORITY		250
#endif

#endif
